parameters:
  - name: 'javaVersion'
    displayName: 'jdk version'
    type: 'string'
    default: ''
  - name: 'Goal'
    displayName: 'maven goal'
    type: 'string'
    default: 'verify' 
  - name: 'testResultspath'
    displayName: 'testResultsFiles'
    type: 'string'
    default: '**/*.xml'
  - name: 'publishJUnitResults'
    displayName: 'publishJUnitResults'
    type: 'string'
    default: true
  - name: 'copyfilecontent'
    displayName: 'CopyFiles'
    type: 'string'
    default: '**/*.jar'

jobs:
  - job: 'BUILD_JOB'
    displayName: 'BUILD_JOB'
    steps:
      - task: Maven@4
        inputs:
          mavenPOMFile: 'pom.xml' 
          goals: ${{ parameters.Goal }}
          publishJUnitResults: ${{ parameters.publishJUnitResults }}
          testResultsFiles: ${{ parameters.testResultspath }}
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: ${{ parameters.javaVersion }}
          condition: ne(${{ parameters.javaVersion }}, '')
      - task: Maven@4
        inputs:
          mavenPOMFile: 'pom.xml' 
          goals: ${{ parameters.Goal }}
          publishJUnitResults: ${{ parameters.publishJUnitResults }}
          testResultsFiles: ${{ parameters.testResultspath }}
          condition: eq(${{ parameters.javaVersion }}, '')
      - task: CopyFiles@2
        inputs:
          Contents: ${{ parameters.copyfilecontent }}
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'snapshot-$(Build.Repository.Name)'