parameters:
  - name: 'pool'
    displayName: 'agent pool'
    type: 'string'
    default: 'Default'
  - name: 'image'
    displayName: 'vmimage'
    type: 'string'
    default: 'ubuntu-24.04'
  - name: 'javaVersion'
    displayName: 'jdk version'
    type: 'string'
    default: '1.17'
  - name: 'Goal'
    displayName: 'maven goal'
    type: 'string'
    default: 'verify' 

jobs:
  - job: 'BUILD_JOB'
    pool:
      name: ${{ parameters.pool }}
      vmImage: 'ubuntu-24.04'
    displayName: 'BUILD_JOB'
    steps:
      - task: Maven@4
        condition: eq(${{ parameters.pool }}, 'Default')
        inputs:
          mavenPOMFile: 'pom.xml' 
          goals: ${{ parameters.Goal }}
          publishJUnitResults: true
          testResultsFiles: '**/*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: ${{ parameters.javaVersion }}
      - task: Maven@4
        condition: and(ne(${{ parameters.pool }}, 'Default'), startsWith(${{ parameters.image }}, 'ubuntu'))
        inputs:
          mavenPOMFile: 'pom.xml' 
          goals: ${{ parameters.Goal }}
          publishJUnitResults: true
          testResultsFiles: '**/*.xml'
      - task: CopyFiles@2
        inputs:
          Contents: '**/*.jar'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'snapshot-$(Build.Repository.Name)'